### ISSUE TITLE
Backward pass through all iteration?

### ISSUE THREAD

**Issue by FeiGSSS** [bwilder0/clusternet#1]
Hi,
Thanks for opening your source codes!
I checked the implementation of the backward passing of gradient, which is calculated using the implicit function theorem in your paper. BUT it seems that your codes directly backpropagate the loss through the iterations in `cluster` and doesn't replace the \partial \mu / \partial x with the partial derivative at the fix-point?

Did I miss something?

**Comment by bwilder0** [comment]
Thanks for your interest in the work! As explained in the paper (Proposition 1), backpropagating through the last clustering iteration provably approximates the gradients that would be obtained via the implicit function theorem.
